
name: Run Telegram Bot
on:
  workflow_dispatch:  # Allows manual triggers
  schedule:
    - cron: '0 */6 * * *'  # Restart every 6 hours
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Check out your code
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node.js 18
      - name: Install dependencies
        run: npm install
      - name: Run Bot
        run: node bot.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Use GitHub Secrets
